(provide 'my-predictive-mode)
(add-to-list 'load-path "~/.emacs.d/predictive/")
(add-to-list 'load-path "~/.emacs.d/predictive/latex/")
(add-to-list 'load-path "~/.emacs.d/predictive/texinfo/")
(add-to-list 'load-path "~/.emacs.d/predictive/html/") 
(require 'predictive)
(autoload 'predictive-mode "predictive" "predictive" t)
;; (set-default 'predictive-auto-add-to-dict t)
;; (setq predictive-use-buffer-local-dict t)
;; (setq predictive-buffer-local-learn-multiplier 60)
;; (setq predictive-auto-learn t)
;; (setq predictive-add-to-dict-ask nil)
;; (setq predictive-use-auto-learn-cache nil)
;; (setq predictive-which-dict t)
