(provide 'my-w3m)
(add-to-list 'load-path "/usr/pbi/emacs-i386/share/emacs/site-lisp/w3m")
(autoload 'w3m "w3m" "Interface for w3m on Emacs." t)
(require 'w3m-load)
(setq browse-url-browser-function 'w3m-browse-url)
(global-set-key "\C-xm" 'browse-url-at-point)
(setq w3m-use-cookies t)
(autoload 'browse-url-interactive-arg "browse-url")
(defun w3m-copy-url-at-point ()
    (interactive)
    (let ((url (w3m-anchor)))
      (if (w3m-url-valid url)
  	  (kill-new (w3m-anchor))
        (message "No URL at point!"))))
(add-hook 'w3m-mode-hook
	  (lambda ()
	    (local-set-key "\M-W" 'w3m-copy-url-at-point)))
(w3m-lnum-mode 1)
